version: '3.4'

volumes:
  ipfs_data_mainnet: {}
  ipfs_data_rinkeby: {}
  
services:
  ipfsconsortium_mainnet:
    image: eduadiez/ipfsconsortium
    volumes:
      - ipfs_data_mainnet:/data/ipfs
    environment:
      - IPFS_ENABLE=true
      - WEB3HOSTWS=wss://mainnet.infura.io/ws
      - CONTRACTADDRESS=0x7433c7c768be4025ab791fb7b2942c3d9e309f3e
      - STARTBLOCK=4090116
    ports:
      - 4001:4001
      - 4002:4002/udp
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
  ipfsconsortium_rinkeby:
    image: eduadiez/ipfsconsortium
    volumes:
      - ipfs_data_rinkeby:/data/ipfs
    environment:
      - IPFS_ENABLE=true
      - WEB3HOSTWS=wss://rinkeby.infura.io/ws
      - CONTRACTADDRESS=0x3ef882ffcE8fC40f6Ca473f29AC16dE8a60419BB
      - STARTBLOCK=1846107
    ports:
      - 4101:4001
      - 4102:4002/udp
      - "127.0.0.1:5101:5001"
      - "127.0.0.1:8180:8080"